version: '3.2'
services:
  app:
    build: ./app
    image: app
    expose:
      - "8000"
  db:
    build: ./db
    image: db
    expose:
      - "3306"
    links:
      - app 
  rproxy:
    image: nginx
    volumes:
      - ./rproxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    links:
     - app
