apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: rproxy
  name: rproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rproxy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rproxy
    spec:
      containers:
      - image: nginx
        name: rproxy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: rproxy-claim0
      restartPolicy: Always
      volumes:
      - name: rproxy-claim0
        hostPath:
          path: /k8s/nginx/
          type: Directory
status: {}
